global:
  hosts:
    https: true
  ingress:
    configureCertmanager: false
    enabled: false
    tls:
      enabled: true
  operator:
    enabled: true
  psql:
    password:
      secret: gitlab-postgres-secret # https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/installation/secrets.md#postgresql-secret
      key: password
    port: 5432
  minio:
    enabled: false
  registry:
    bucket: ""
  appConfig:
    omniauth:
      enabled: true
      allowSingleSignOn: ['saml']
      blockAutoCreatedUsers: false
      autoLinkLdapUser: true
      autoLinkSamlUser: true
      providers:
      - secret: gitlab-onelogin
        key: provider
    lfs:
      bucket: ""
      connection: # https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/charts/globals.md#connection
        secret: gitlab-rails-storage
        key: connection
    artifacts:
      bucket: ""
      connection:
        secret: gitlab-rails-storage
        key: connection
    uploads:
      bucket: ""
      connection:
        secret: gitlab-rails-storage
        key: connection
    packages:
      bucket: ""
      connection:
        secret: gitlab-rails-storage
        key: connection
    backups:
      bucket: ""
      tmpBucket: ""
  smtp:
    enabled: true
    address: ""
    port: 587
    user_name: ""
    ## doc/installation/secrets.md#smtp-password
    password:
      secret: gitlab-smtp
      key: password
    authentication: "plain"
    starttls_auto: true
    openssl_verify_mode: "peer"

gitlab:
  gitaly:
    replicas: 2
  task-runner:
    backups:
      objectStorage:
        config:
          secret: storage-config
          key: config
registry:
  storage:
    secret: gitlab-registry-storage
    key: config
redis:
  cluster:
    enabled: true
postgresql:
  install: false
certmanager:
  install: false
nginx-ingress:
  enabled: true
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
gitlab-runner:
  install: true
  concurrent: 10
  checkInterval: 30
  unregisterRunners: true
  runners:
    image: "alpine:latest"
    privileged: true
    pollTimeout: 3600
    envVars:
    - name: KUBERNETES_POLL_INTERVAL
      value: 15
